input {
  file {
    path => "/var/log/honeypot/ssh_single_line.jsonl"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "plain"
  }
}

filter {
  # Décoder la ligne JSON contenue dans [message] vers [doc]
  json {
    source => "message"
    target => "doc"
  }

  # Timestamp d’ingestion
  mutate {
    add_field => { "ingest_time" => "%{@timestamp}" }
  }

  # Recopier quelques champs utiles de [doc] vers la racine
  if [doc][event] {
    mutate { add_field => { "event" => "%{[doc][event]}" } }
  }
  if [doc][src_ip] {
    mutate {
      add_field => {
        "src_ip"    => "%{[doc][src_ip]}"
        "source.ip" => "%{[doc][src_ip]}"
      }
    }
  }
  if [doc][username] {
    mutate {
      add_field => {
        "username"  => "%{[doc][username]}"
        "user.name" => "%{[doc][username]}"
      }
    }
  }
  if [doc][src_port] {
    mutate { convert => { "[doc][src_port]" => "integer" } }
  }

  # Gérer le timestamp du honeypot
  if [doc][timestamp] {
    mutate { rename => { "[doc][timestamp]" => "[doc][honeypot_timestamp]" } }
    date {
      match   => ["[doc][honeypot_timestamp]", "ISO8601"]
      target  => "@timestamp"
      timezone => "UTC"
    }
  }

  # Taguer les erreurs serveur
  if [doc][event] == "server_error" {
    mutate { add_tag => ["honeypot_error"] }
  }

  # Détection brute-force : 5 tentatives/minute par IP
  if [doc][event] == "auth_attempt" {
    aggregate {
      task_id => "%{[doc][src_ip]}"
      code => "
        map['count'] ||= 0
        map['first_ts'] ||= event.get('@timestamp')
        map['count'] += 1

        if map['count'] >= 5
          event.set('bruteforce', true)
          event.set('bruteforce_count', map['count'])
          event.set('bruteforce_ip', event.get('[doc][src_ip]'))
          event.set('bruteforce_first_ts', map['first_ts'])
        end
      "
      timeout_task_id_field => "[doc][src_ip]"
      timeout => 60
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "honeypot-ssh-clean-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
